routes/web.php
<?php

use Illuminate\Http\File;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UserController;
use App\Http\Controllers\Users\ProfileController;
use App\Http\Controllers\Users\RoleController;
use App\Http\Controllers\Users\MessageController;
use App\Http\Controllers\Users\NotificationController;
use App\Http\Controllers\Site\HomeController;
use App\Http\Controllers\Site\DashboardController;
use App\Http\Controllers\Site\SubjectController;
use App\Http\Controllers\Site\WidgetController;
use App\Http\Controllers\Site\PageController;
use App\Http\Controllers\Site\OrderFieldController;
use App\Http\Controllers\Projects\OrderController;
use App\Http\Controllers\Projects\TaskController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', [WelcomeController::class, 'index'])->name('welcome');
Route::get('/', [HomeController::class, 'index'])->name('home');
Route::get('home', [HomeController::class, 'index'])->name('home');
Route::get('order', [HomeController::class, 'order'])->name('order');
Route::put('ordernow', [HomeController::class, 'orderNow'])->name('ordernow');

Auth::routes();

Route::group(['middleware' => 'auth'], function () {
    Route::get('dashboard', [DashboardController::class, 'index'])->name('dashboard');

    Route::group(['prefix' => 'profile', 'as' => 'profile.'], function () {
        Route::get('/', [ProfileController::class, 'edit'])->name('edit');
        Route::put('/', [ProfileController::class, 'update'])->name('update');
        Route::put('password', [ProfileController::class, 'password'])->name('password');    
    });
    
    Route::resource('users', UserController::class, ['except' => ['show']]);
    Route::resource('roles', RoleController::class, ['except' => ['show', 'destroy']]);
    Route::resource('messages', MessageController::class, ['except' => ['show']]);
    Route::resource('notifications', NotificationController::class, ['except' => ['show']]);

    Route::resource('subjects', SubjectController::class, ['except' => ['show']]);
    Route::resource('widgets', WidgetController::class, ['except' => ['show']]);
    Route::resource('pages', PageController::class, ['except' => ['show']]);
    Route::resource('orderfields', OrderFieldController::class, ['except' => ['show']]);

    Route::resource('orders', OrderController::class, ['except' => ['show']]);
    Route::resource('tasks', TaskController::class, ['except' => ['show']]);
  
});

Route::get('storage/{filename}', function ($filename) {
    $path = storage_path('public/' . $filename);

    if (!File::exists($path)) {
        abort(404);
    }

    $file = File::get($path);
    $type = File::mimeType($path);

    $response = Response::make($file, 200);
    $response->header("Content-Type", $type);

    return $response;
});

app/Models/Site/OrderField.php
<?php

namespace App\Models\Site;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class OrderField extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['label', 'instruction', 'type', 'options', 'attributes', 'default_value', 'position', 'enabled'];
    
    /**
     * Get the users for the role
     *
     * @return void
     */
    public function users()
    {
        return $this->hasMany(User::class);
    }
}

app/Http/Controllers/Site/DashboardController.php
<?php

namespace App\Http\Controllers\Site;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class DashboardController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('site.dashboard');
    }
}

app/Http/Controllers/Site/HomeController.php
<?php

namespace App\Http\Controllers\Site;

use App\Models\Projects\Order;
use App\Models\Site\OrderField;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class HomeController extends Controller
{
  
    /**
     * Show the application home.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('site.home');
    }

    /**
     * Show the form for creating a new order
     *
     * @return \Illuminate\View\View
     */
    public function order()
    {
        $html_fields = '';
        $fields = OrderField::where('enabled', 1)->get();

        foreach($fields as $field)
        {
            $html_fields .= "\n";
            $html_fields .= '<div class="row">';
            $html_fields .= '<div class="col-sm-12">';
            $html_fields .= '<div class="form-group bmd-form-group field-' . $field->id .'-error " >';
            $html_fields .= "\n";

            $html_options = array();

            if (isset($field->options))
            {
                $html_options = explode('||', $field->options);
            }

            switch ($field->type)
            {
                case 'number':
                    $html_fields .= '<label>' . $field->label . '</label>';
                    $html_fields .= "\n";
                    $html_fields .= '<input type="number" class="form-control" id="field-' . $field->id .'" name="field-' . $field->id .'">';
                    break;

                case 'textarea':
                    $html_fields .= '<label>' . $field->label . '</label>';
                    $html_fields .= "\n";
                    $html_fields .= '<textarea class="form-control" id="field-' . $field->id .'" name="field-' . $field->id .'"></textarea>';
                    break;
    
                case 'checkbox':
                    $html_fields .= '<label class="form-check-label">';
                    $html_fields .= "\n";
                    $html_fields .= '<input class="form-check-input" type="checkbox" name="policy" value="1">
                    <span class="form-check-sign">
                      <span class="check"></span>
                    </span>I agree with the <a href="#">terms and conditions</a>
                  </label>';
                    break;

                case 'select':
                    $html_fields .= '<label>' . $field->label . '</label>';
                    $html_fields .= "\n";
                    $html_fields .= '<select class="selectpicker col-sm-12 pl-0 pr-0" data-style="select-with-transition" title="" data-size="100" id="field-' . $field->id .'" name="field-' . $field->id .'">';
                    $html_fields .= "\n";

                    foreach($html_options as $html_option)
                    {
                        $option = explode('#', trim($html_option));
                        $html_fields .= '<option value="' . $option[0] . '">' . $option[1] . '</option>';
                        $html_fields .= "\n";
                    }
                    $html_fields .= '</select>';
                    break;

                case 'select-radio':
                    $html_fields .= '<label>' . $field->label . '</label>';
                    $html_fields .= "\n";
                    foreach($html_options as $html_option)
                    {
                        $option = explode('#', trim($html_option));
                        $html_fields .= '<input type="radio" class="form-control" id="field-' . $field->id .'" name="field-' . $field->id .'" value="' . $option[0]. '">' . $option[1];
                        $html_fields .= "\n";
                    }
                    break;
                
                default:
                    $html_fields .= '<label>' . $field->label . '</label>';
                    $html_fields .= "\n";
                    $html_fields .= '<input type="text" class="form-control" id="field-' . $field->id .'" name="field-' . $field->id .'">';
                    break;
            }

            $html_fields .= "\n";
            $html_fields .= '</div>';
            $html_fields .= '</div>';
            $html_fields .= '</div>';
            $html_fields .= "\n";
        }

        return view('site.order', compact('html_fields'));
    }

    /**
     * Store a newly created order in storage
     *
     * @param  \App\Http\Requests\Request  $request
     * @param  \App\Models\Order $order
     * @return \Illuminate\Http\RedirectResponse
     */
    public function orderNow(Request $request)
    {
        try {
            $fields = OrderField::where('enabled', 1)->get();
            $fullorder = '';
            foreach($fields as $field)
            {
                $fullorder .= $field->label . ': ';
                $fullorder .= $request[$field->id];
                $fullorder .= '||';
            }

            Order::create([
                'name' => 'PRH Order',
                'content' => $fullorder,
            ]);
            return redirect()->route('home')->withStatus(__('Your Order was successfully submitted.'));
        } catch (\Exception $exception) {
            return redirect()->back()->withError('Error while creating Order');
        }
    }

}

app/Http/Controllers/Site/OrderFieldController.php
<?php

namespace App\Http\Controllers\Site;

use App\Models\User;
use App\Models\Site\OrderField;
use App\Http\Controllers\Controller;
use App\Http\Requests\OrderFieldRequest;

class OrderFieldController extends Controller
{
    public function __construct()
    {
        $this->authorizeResource(OrderField::class);
    }

    /**
     * Display a listing of the orderfields
     *
     * @param \App\Models\OrderField  $model
     * @return \Illuminate\View\View
     */
    public function index(OrderField $orderfields)
    {
        $this->authorize('manage-orderfields', User::class);

        return view('site.orderfields.index', ['orderfields' => $orderfields->all()]);
    }

    /**
     * Show the form for creating a new orderfield
     *
     * @return \Illuminate\View\View
     */
    public function create()
    {
        return view('site.orderfields.create');
    }

    /**
     * Store a newly created orderfield in storage
     *
     * @param  \App\Http\Requests\OrderFieldRequest  $request
     * @param  \App\Models\OrderField  $model
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(OrderFieldRequest $request, OrderField $orderfield)
    {
        try {
            $lines = preg_split('/\r\n|\r|\n/', $request['options']);

            OrderField::create([
                'label' => $request['label'],
                'type' => $request['type'],
                'instruction' => isset($request['instruction']) ? $request['instruction'] : null,
                'attributes' => isset($request['attributes']) ? $request['attributes'] : null,
                'default_value' => isset($request['default_value']) ? $request['default_value'] : null,
                'options' => isset($request['options']) ? implode(' || ', $lines) : null,
                'position' => $request['position'],
                'enabled' => 1,
            ]);
            return redirect()->route('orderfields.index')->withStatus(__('Order Field successfully created.'));
        } catch (\Exception $exception) {
            return redirect()->back()->withError('Error while creating Order Field');
        }
    }

    /**
     * Show the form for editing the specified orderfield
     *
     * @param  \App\Models\OrderField  $orderfield
     * @return \Illuminate\View\View
     */
    public function edit(OrderField $orderfield)
    {
        return view('site.orderfields.edit', compact('orderfield'));
    }

    /**
     * Update the specified orderfield in storage
     *
     * @param  \App\Http\Requests\OrderFieldRequest  $request
     * @param  \App\Models\OrderField  $orderfield
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(OrderFieldRequest $request, OrderField $orderfield)
    {
        try {
            $lines = preg_split('/\r\n|\r|\n/', $request['options']);

            $orderfield->label = $request['label'];
            $orderfield->type = $request['type'];
            $orderfield->instruction = isset($request['instruction']) ? $request['instruction'] : '';
            $orderfield->attributes = isset($request['attributes']) ? $request['attributes'] : '';
            $orderfield->default_value = isset($request['default_value']) ? $request['default_value'] : '';
            $orderfield->options = isset($request['options']) ? implode(' || ', $lines) : '';
            $orderfield->position = $request['position'];
            $orderfield->enabled = 1;
            $orderfield->update();

            return redirect()->route('site.orderfields.index')->withStatus(__('Order Field successfully updated.'));
        } catch (\Exception $exception) {
            return redirect()->back()->withError('Error while updating Order Field');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\OrderField  $apptime
     * @return \Illuminate\Http\Response
     */
    public function destroy(OrderField $orderfield)
    {
        $orderfield->delete();

        return redirect()->route('site.orderfields.index')->withStatus(__('Order Field deleted successfully.'));
    }
}

app/Http/Controllers/Site/PageController.php
<?php

namespace App\Http\Controllers\Site;

use App\Models\User;
use App\Models\Site\Page;
use App\Http\Controllers\Controller;
use App\Http\Requests\PageRequest;

class PageController extends Controller
{
    public function __construct()
    {
        $this->authorizeResource(Page::class);
    }

    /**
     * Display a listing of the pages
     *
     * @param \App\Models\Page  $model
     * @return \Illuminate\View\View
     */
    public function index(Page $page)
    {
        $this->authorize('manage-pages', User::class);

        return view('site.pages.index', ['pages' => $page->all()]);
    }

    /**
     * Show the form for creating a new page
     *
     * @return \Illuminate\View\View
     */
    public function create()
    {
        return view('site.pages.create');
    }

    /**
     * Store a newly created page in storage
     *
     * @param  \App\Http\Requests\PageRequest  $request
     * @param  \App\Models\Page  $model
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(PageRequest $request, Page $page)
    {
        $page->create($request->all());

        return redirect()->route('pages.index')->withStatus(__('Page successfully created.'));
    }

    /**
     * Show the form for editing the specified page
     *
     * @param  \App\Models\Page  $page
     * @return \Illuminate\View\View
     */
    public function edit(Page $page)
    {
        return view('site.pages.edit', compact('page'));
    }

    /**
     * Update the specified page in storage
     *
     * @param  \App\Http\Requests\PageRequest  $request
     * @param  \App\Models\Page  $page
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(PageRequest $request, Page $page)
    {
        $page->update($request->all());

        return redirect()->route('site.pages.index')->withStatus(__('Page successfully updated.'));
    }
}

app/Http/Controllers/Site/SubjectController.php
<?php

namespace App\Http\Controllers\Site;

use App\Models\User;
use App\Models\Site\Subject;
use App\Http\Controllers\Controller;
use App\Http\Requests\SubjectRequest;

class SubjectController extends Controller
{
    public function __construct()
    {
        $this->authorizeResource(Subject::class);
    }

    /**
     * Display a listing of the subjects
     *
     * @param \App\Models\Subject  $model
     * @return \Illuminate\View\View
     */
    public function index(Subject $subject)
    {
        $this->authorize('manage-subjects', User::class);

        return view('site.subjects.index', ['subjects' => $subject->all()]);
    }

    /**
     * Show the form for creating a new subject
     *
     * @return \Illuminate\View\View
     */
    public function create()
    {
        return view('site.subjects.create');
    }

    /**
     * Store a newly created subject in storage
     *
     * @param  \App\Http\Requests\SubjectRequest  $request
     * @param  \App\Models\Subject  $model
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(SubjectRequest $request, Subject $subject)
    {
        $subject->create($request->all());

        return redirect()->route('site.subjects.index')->withStatus(__('Subject successfully created.'));
    }

    /**
     * Show the form for editing the specified subject
     *
     * @param  \App\Models\Subject  $subject
     * @return \Illuminate\View\View
     */
    public function edit(Subject $subject)
    {
        return view('site.subjects.edit', compact('subject'));
    }

    /**
     * Update the specified subject in storage
     *
     * @param  \App\Http\Requests\SubjectRequest  $request
     * @param  \App\Models\Subject  $subject
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(SubjectRequest $request, Subject $subject)
    {
        $subject->update($request->all());

        return redirect()->route('site.subjects.index')->withStatus(__('Subject successfully updated.'));
    }
}

resources/views/site/widgets/create.blade.php
@extends('layouts.app', ['activePage' => 'widget-management', 'menuParent' => 'laravel', 'titlePage' => __('Widget Management')])

@section('content')
  <div class="content">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-12">
          <form method="post" action="{{ route('widgets.store') }}" autocomplete="off" class="form-horizontal">
            @csrf
            @method('post')

            <div class="card ">
              <div class="card-header card-header-rose card-header-icon">
                <div class="card-icon">
                  <i class="material-icons">recent_actors</i>
                </div>
                <h4 class="card-title">{{ __('Add Widget') }}</h4>
              </div>
              <div class="card-body ">
                <div class="row">
                  <div class="col-md-12 text-right">
                      <a href="{{ route('widgets.index') }}" class="btn btn-sm btn-rose">{{ __('Back to list') }}</a>
                  </div>
                </div>
                <div class="row">
                  <label class="col-sm-2 col-form-label">{{ __('Name') }}</label>
                  <div class="col-sm-7">
                    <div class="form-group{{ $errors->has('name') ? ' has-danger' : '' }}">
                      <input class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" name="name" id="input-name" type="text" placeholder="{{ __('Name') }}" value="{{ old('name') }}" required="true" aria-required="true"/>
                      @include('alerts.feedback', ['field' => 'name'])
                    </div>
                  </div>
                </div>
                <div class="row">
                  <label class="col-sm-2 col-form-label">{{ __('Description') }}</label>
                  <div class="col-sm-7">
                    <div class="form-group{{ $errors->has('description') ? ' has-danger' : '' }}">
                      <textarea cols="30" rows="10" class="form-control{{ $errors->has('description') ? ' is-invalid' : '' }}" name="description" id="input-description" type="text" placeholder="{{ __('Description') }}" required="true" aria-required="true">{{ old('description') }}</textarea>
                      @include('alerts.feedback', ['field' => 'description'])
                    </div>
                  </div>
                </div>
              </div>
              <div class="card-footer ml-auto mr-auto">
                <button type="submit" class="btn btn-rose">{{ __('Save') }}</button>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
@endsection

resources/views/site/widgets/edit.blade.php
@extends('layouts.app', ['activePage' => 'widget-management', 'menuParent' => 'laravel', 'titlePage' => __('Widget Management')])

@section('content')
  <div class="content">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-12">
          <form method="post" action="{{ route('widgets.update', $widget) }}" autocomplete="off" class="form-horizontal">
            @csrf
            @method('put')

            <div class="card ">
              <div class="card-header card-header-rose card-header-icon">
                <div class="card-icon">
                  <i class="material-icons">recent_actors</i>
                </div>
                <h4 class="card-title">{{ __('Edit Widget') }}</h4>
              </div>
              <div class="card-body ">
                <div class="row">
                  <div class="col-md-12 text-right">
                      <a href="{{ route('widgets.index') }}" class="btn btn-sm btn-rose">{{ __('Back to list') }}</a>
                  </div>
                </div>
                <div class="row">
                  <label class="col-sm-2 col-form-label">{{ __('Name') }}</label>
                  <div class="col-sm-7">
                    <div class="form-group{{ $errors->has('name') ? ' has-danger' : '' }}">
                      <input class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" name="name" id="input-name" type="text" placeholder="{{ __('Name') }}" value="{{ old('name', $widget->name) }}" required="true" aria-required="true"/>
                      @include('alerts.feedback', ['field' => 'name'])
                    </div>
                  </div>
                </div>
                <div class="row">
                  <label class="col-sm-2 col-form-label">{{ __('Description') }}</label>
                  <div class="col-sm-7">
                    <div class="form-group{{ $errors->has('description') ? ' has-danger' : '' }}">
                      <textarea cols="30" rows="10" class="form-control{{ $errors->has('description') ? ' is-invalid' : '' }}" name="description" id="input-description" type="text" placeholder="{{ __('Description') }}" required="true" aria-required="true">{{ old('description', $widget->description) }}</textarea>
                      @include('alerts.feedback', ['field' => 'description'])
                    </div>
                  </div>
                </div>
              </div>
              <div class="card-footer ml-auto mr-auto">
                <button type="submit" class="btn btn-rose">{{ __('Save') }}</button>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
@endsection

resources/views/site/widgets/index.blade.php
@extends('layouts.app', ['activePage' => 'widget-management', 'menuParent' => 'laravel', 'titlePage' => __('Widget Management')])

@section('content')
  <div class="content">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-12">
            <div class="card">
              <div class="card-header card-header-rose card-header-icon">
                <div class="card-icon">
                  <i class="material-icons">recent_actors</i>
                </div>
                <h4 class="card-title">{{ __('Widgets') }}</h4>
              </div>
              <div class="card-body">
                @can('create', App\Models\Widget::class)
                  <div class="row">
                    <div class="col-12 text-right">
                      <a href="{{ route('widgets.create') }}" class="btn btn-sm btn-rose">{{ __('Add A Widget') }}</a>
                    </div>
                  </div>
                @endcan
                <div class="table-responsive">
                  <table id="datatables" class="table table-striped table-no-bordered table-hover" style="display:none">
                    <thead class="text-primary">
                      <th>
                          {{ __('Name') }}
                      </th>
                      <th>
                        {{ __('Description') }}
                      </th>
                      <th>
                        {{ __('Creation date') }}
                      </th>
                      @can('manage-widgets', App\Models\User::class)
                        <th class="text-right">
                          {{ __('Actions') }}
                        </th>
                      @endcan
                    </thead>
                    <tbody>
                      @foreach($widgets as $widget)
                        <tr>
                          <td>
                            {{ $widget->name }}
                          </td>
                          <td>
                            {{ $widget->description }}
                          </td>
                          <td>
                            {{ $widget->created_at->format('Y-m-d') }}
                          </td>
                          @can('manage-widgets', App\Models\User::class)
                            <td class="td-actions text-right">
                              @can('update', $widget)
                                <a rel="tooltip" class="btn btn-success btn-link" href="{{ route('widgets.edit', $widget) }}" data-original-title="" title="">
                                  <i class="material-icons">edit</i>
                                  <div class="ripple-container"></div>
                                </a>
                              @endcan
                            </td>
                          @endcan
                        </tr>
                      @endforeach
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
        </div>
      </div>
    </div>
  </div>
@endsection

@push('js')
<script>
  $(document).ready(function() {
    $('#datatables').fadeIn(1100);
    $('#datatables').DataTable({
      "pagingType": "full_numbers",
      "lengthMenu": [
        [10, 25, 50, -1],
        [10, 25, 50, "All"]
      ],
      responsive: true,
      language: {
        search: "_INPUT_",
        searchPlaceholder: "Search Widgets",
      },
      "columnDefs": [
        { "orderable": false, "targets": 3 },
      ],
    });
  });
</script>
@endpush